\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{watson}
\LoadClass[titlepage]{article}

\RequirePackage[margin=3cm]{geometry}
\RequirePackage[toc,page]{appendix}
\RequirePackage[nottoc]{tocbibind}
\RequirePackage[utf8]{inputenc}
\RequirePackage{etoolbox}
\RequirePackage{lmodern}
\RequirePackage{setspace}
\RequirePackage{caption}

% Differentiate caption text from body text
\captionsetup{font=footnotesize}
% Change line spacing
\setstretch{1.2}
